---
- name: Start from fresh forwardingStatus CSV
  delegate_to: localhost
  run_once: true
  shell: sed -i '/fqdn,version,time,rc/,$d' /tmp/ansible/syslog/forwardingStatus.csv

- name: Confirm that forwardLogs are correctly configured
  shell: grep -q 10.150.202.11 /etc/rsyslog.d/forwardLogs.conf
  ignore_errors: true
  register: forwardingStatus

- name: Dump output to CSV
  delegate_to: localhost
  lineinfile:
    path: /tmp/ansible/syslog/forwardingStatus.csv
    line: '{{ hostvars[inventory_hostname_short]['ansible_facts']['fqdn'] }},{{ forwardingStatus.end }}, {{ forwardingStatus.rc }}'
    insertafter: rc
#  copy:
#    content: "{{ forwardingStatus | to_nice_json }}"
#    dest: "/tmp/ansible/syslog/{{ hostvars[inventory_hostname_short]['ansible_facts']['fqdn'] }}_syslog_forwarding_status.csv"
