---
- name: Start from fresh forwardingStatus CSV
  run_once: true
  local_action: command sed -i '2,$d' /tmp/ansible/syslog/forwardingStatus.csv

- name: Confirm that forwardLogs are correctly configured
  shell: grep -q 10.150.202.11 /etc/rsyslog.d/forwardLogs.conf
  ignore_errors: true
  register: forwardingStatus

- name: Grab config version
# TO DO: determine how to grab version
  shell: grep -q version /etc/rsyslog.d/forwardLogs.conf
  ignore_errors: true
  register: configVersion

- name: Add to forwardStatus report
  delegate_to: localhost
  lineinfile:
    path: /tmp/ansible/syslog/forwardingStatus.csv
    line: "{{ hostvars[inventory_hostname_short]['ansible_facts']['fqdn'] }},{{ configVersion.stdout }},{{ forwardingStatus.end }},{{ forwardingStatus.rc }}""
    insertafter: fqdn,version,time,rc