version: "3.2"
services:
  svr:
    container_name: ansible_svr
    build:
      context: Dockerfiles
      dockerfile: ansible
    image: local:ansible
    networks:
      - default
  test_container_1:
    container_name: test_container_1
    build:
      context: Dockerfiles
      dockerfile: ssh
    image: local:sshd
    ports:
      - "2222:22"
    expose:
      - 22
    networks:
      - default
  test_container_2:
    container_name: test_container_2
    build:
      context: Dockerfiles
      dockerfile: ssh
    image: local:sshd
    ports:
      - "2223:22"
    expose:
      - 22
    networks:
      - default
    
networks:
   default:
